import { CardTemplate, TemplateCategory } from "./types";

export const TEMPLATE_CATEGORIES: TemplateCategory[] = [
  "Elegan",
  "Islamik",
  "Korporat",
  "Minimalis",
  "Floral",
  "Gold Luxury",
  "Batik",
  "Melayu Tradisional",
  "Modern Glass",
  "Premium Dark",
  "Royal",
  "Soft Pastel"
];

// Generate 50 unique premium templates across the 12 categories
export const PREMIUM_TEMPLATES: CardTemplate[] = [
  // 1. Gold Luxury (5 templates)
  {
    id: "gold-luxury-1",
    name: "Mahkota Emas Klasik",
    category: "Gold Luxury",
    primaryColor: "#DFBA54",
    secondaryColor: "#111111",
    accentColor: "#F5D77F",
    backgroundColor: "linear-gradient(135deg, #111111 0%, #2a220f 100%)",
    textColor: "#F5D77F",
    fontFamily: "Playfair Display",
    frameStyle: "royal",
    borderStyle: "double",
    particleType: "golden",
    bgPattern: "luxury-gold"
  },
  {
    id: "gold-luxury-2",
    name: "Lace Emas Putih",
    category: "Gold Luxury",
    primaryColor: "#DFBA54",
    secondaryColor: "#FFFFFF",
    accentColor: "#EAD087",
    backgroundColor: "linear-gradient(135deg, #FFFFFF 0%, #FFFDF6 100%)",
    textColor: "#3A331E",
    fontFamily: "Great Vibes",
    frameStyle: "floral",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "gold-luxury-3",
    name: "Emerald Gold",
    category: "Gold Luxury",
    primaryColor: "#DFBA54",
    secondaryColor: "#062E03",
    accentColor: "#F0E2A1",
    backgroundColor: "linear-gradient(135deg, #021a01 0%, #0c3608 100%)",
    textColor: "#F0E2A1",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "solid",
    particleType: "sparkle"
  },
  {
    id: "gold-luxury-4",
    name: "Saphire Gold",
    category: "Gold Luxury",
    primaryColor: "#DFBA54",
    secondaryColor: "#05162E",
    accentColor: "#F2DF9B",
    backgroundColor: "linear-gradient(135deg, #020b18 0%, #0e274c 100%)",
    textColor: "#F2DF9B",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "double",
    particleType: "sparkle"
  },
  {
    id: "gold-luxury-5",
    name: "Ruby Gold Luxury",
    category: "Gold Luxury",
    primaryColor: "#DFBA54",
    secondaryColor: "#2A0202",
    accentColor: "#FCE7A2",
    backgroundColor: "linear-gradient(135deg, #180101 0%, #3a0808 100%)",
    textColor: "#FCE7A2",
    fontFamily: "Montserrat",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },

  // 2. Islamik (5 templates)
  {
    id: "islamik-1",
    name: "Kubah Safawi",
    category: "Islamik",
    primaryColor: "#0D5C3A",
    secondaryColor: "#DFBA54",
    accentColor: "#F2DC99",
    backgroundColor: "linear-gradient(135deg, #073822 0%, #15794e 100%)",
    textColor: "#FFFFFF",
    fontFamily: "Amiri",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "firefly"
  },
  {
    id: "islamik-2",
    name: "Arches Andalus",
    category: "Islamik",
    primaryColor: "#1A4C62",
    secondaryColor: "#D1A153",
    accentColor: "#EBC384",
    backgroundColor: "linear-gradient(135deg, #0b2633 0%, #286b87 100%)",
    textColor: "#F9F6F0",
    fontFamily: "Amiri",
    frameStyle: "classic",
    borderStyle: "double",
    particleType: "sparkle"
  },
  {
    id: "islamik-3",
    name: "Hiasan Arabesque",
    category: "Islamik",
    primaryColor: "#C19A5B",
    secondaryColor: "#2F2F2F",
    accentColor: "#FFFDF9",
    backgroundColor: "linear-gradient(135deg, #1C1C1C 0%, #333333 100%)",
    textColor: "#E5C185",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "islamik-4",
    name: "Najah Hijau Suci",
    category: "Islamik",
    primaryColor: "#0F7A50",
    secondaryColor: "#EAEAEA",
    accentColor: "#139C66",
    backgroundColor: "#FFFFFF",
    textColor: "#0A4E33",
    fontFamily: "Amiri",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "flower"
  },
  {
    id: "islamik-5",
    name: "Sutera Kaabah",
    category: "Islamik",
    primaryColor: "#DFBA54",
    secondaryColor: "#000000",
    accentColor: "#FFEBB2",
    backgroundColor: "linear-gradient(135deg, #151515 0%, #000000 100%)",
    textColor: "#DFBA54",
    fontFamily: "Amiri",
    frameStyle: "royal",
    borderStyle: "double",
    particleType: "golden"
  },

  // 3. Floral (5 templates)
  {
    id: "floral-1",
    name: "Mawar Kasih Pink",
    category: "Floral",
    primaryColor: "#EC4899",
    secondaryColor: "#FFF5F7",
    accentColor: "#F472B6",
    backgroundColor: "linear-gradient(135deg, #FFF0F3 0%, #FFE4E6 100%)",
    textColor: "#831843",
    fontFamily: "Great Vibes",
    frameStyle: "floral",
    borderStyle: "ornate",
    particleType: "flower"
  },
  {
    id: "floral-2",
    name: "Eucalyptus Minimal",
    category: "Floral",
    primaryColor: "#65A30D",
    secondaryColor: "#FAFAF9",
    accentColor: "#84CC16",
    backgroundColor: "linear-gradient(135deg, #F7fee7 0%, #f1f5f9 100%)",
    textColor: "#3F6212",
    fontFamily: "Playfair Display",
    frameStyle: "floral",
    borderStyle: "classic",
    particleType: "flower"
  },
  {
    id: "floral-3",
    name: "Golden Rose Luxury",
    category: "Floral",
    primaryColor: "#EAB308",
    secondaryColor: "#781A33",
    accentColor: "#FDE047",
    backgroundColor: "linear-gradient(135deg, #4c0519 0%, #831843 100%)",
    textColor: "#FDE047",
    fontFamily: "Great Vibes",
    frameStyle: "floral",
    borderStyle: "double",
    particleType: "golden"
  },
  {
    id: "floral-4",
    name: "Orkid Putih Berseri",
    category: "Floral",
    primaryColor: "#A855F7",
    secondaryColor: "#FFFFFF",
    accentColor: "#C084FC",
    backgroundColor: "linear-gradient(135deg, #FAF5FF 0%, #F3E8FF 100%)",
    textColor: "#581C87",
    fontFamily: "Montserrat",
    frameStyle: "floral",
    borderStyle: "solid",
    particleType: "sparkle"
  },
  {
    id: "floral-5",
    name: "Sakura Musim Luruh",
    category: "Floral",
    primaryColor: "#F43F5E",
    secondaryColor: "#FFF1F2",
    accentColor: "#FB7185",
    backgroundColor: "#FFFBFB",
    textColor: "#9F1239",
    fontFamily: "Alex Brush",
    frameStyle: "floral",
    borderStyle: "dashed",
    particleType: "flower"
  },

  // 4. Melayu Tradisional (5 templates)
  {
    id: "tradisional-1",
    name: "Songket Diraja",
    category: "Melayu Tradisional",
    primaryColor: "#DFBA54",
    secondaryColor: "#581C87",
    accentColor: "#F3E8FF",
    backgroundColor: "linear-gradient(135deg, #2e0854 0%, #4a157d 100%)",
    textColor: "#DFBA54",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "tradisional-2",
    name: "Ukiran Kayu Jati",
    category: "Melayu Tradisional",
    primaryColor: "#B45309",
    secondaryColor: "#FEF3C7",
    accentColor: "#D97706",
    backgroundColor: "linear-gradient(135deg, #2b1402 0%, #452203 100%)",
    textColor: "#FEF3C7",
    fontFamily: "Playfair Display",
    frameStyle: "classic",
    borderStyle: "ornate",
    particleType: "firefly"
  },
  {
    id: "tradisional-3",
    name: "Pucuk Rebung Silver",
    category: "Melayu Tradisional",
    primaryColor: "#94A3B8",
    secondaryColor: "#0F172A",
    accentColor: "#CBD5E1",
    backgroundColor: "linear-gradient(135deg, #090d16 0%, #1e293b 100%)",
    textColor: "#E2E8F0",
    fontFamily: "Montserrat",
    frameStyle: "classic",
    borderStyle: "double",
    particleType: "sparkle"
  },
  {
    id: "tradisional-4",
    name: "Lentera Warisan",
    category: "Melayu Tradisional",
    primaryColor: "#EA580C",
    secondaryColor: "#FFF7ED",
    accentColor: "#F97316",
    backgroundColor: "linear-gradient(135deg, #1d0700 0%, #431200 100%)",
    textColor: "#FFedd5",
    fontFamily: "Great Vibes",
    frameStyle: "royal",
    borderStyle: "classic",
    particleType: "firefly"
  },
  {
    id: "tradisional-5",
    name: "Tepak Sirih Tembaga",
    category: "Melayu Tradisional",
    primaryColor: "#D97706",
    secondaryColor: "#3F2F11",
    accentColor: "#FBBF24",
    backgroundColor: "linear-gradient(135deg, #1c1507 0%, #2a200a 100%)",
    textColor: "#FDE047",
    fontFamily: "Amiri",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "golden"
  },

  // 5. Batik (4 templates)
  {
    id: "batik-1",
    name: "Batik Canting Emas",
    category: "Batik",
    primaryColor: "#DFBA54",
    secondaryColor: "#1E3A8A",
    accentColor: "#3B82F6",
    backgroundColor: "linear-gradient(135deg, #09122c 0%, #1e3a8a 100%)",
    textColor: "#DFBA54",
    fontFamily: "Great Vibes",
    frameStyle: "classic",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "batik-2",
    name: "Batik Mega Mendung",
    category: "Batik",
    primaryColor: "#0284C7",
    secondaryColor: "#F0F9FF",
    accentColor: "#0EA5E9",
    backgroundColor: "linear-gradient(135deg, #E0F2FE 0%, #BAE6FD 100%)",
    textColor: "#0369A1",
    fontFamily: "Playfair Display",
    frameStyle: "classic",
    borderStyle: "double",
    particleType: "sparkle"
  },
  {
    id: "batik-3",
    name: "Batik Terengganu Klasik",
    category: "Batik",
    primaryColor: "#BE123C",
    secondaryColor: "#FFF1F2",
    accentColor: "#FDA4AF",
    backgroundColor: "linear-gradient(135deg, #fff1f2 0%, #ffe4e6 100%)",
    textColor: "#9F1239",
    fontFamily: "Cinzel",
    frameStyle: "floral",
    borderStyle: "solid",
    particleType: "flower"
  },
  {
    id: "batik-4",
    name: "Sutera Batik Royal",
    category: "Batik",
    primaryColor: "#EAB308",
    secondaryColor: "#3B0764",
    accentColor: "#FDE047",
    backgroundColor: "linear-gradient(135deg, #1e003a 0%, #3b0764 100%)",
    textColor: "#FDE047",
    fontFamily: "Great Vibes",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },

  // 6. Elegan (4 templates)
  {
    id: "elegan-1",
    name: "Vellum Satin",
    category: "Elegan",
    primaryColor: "#0F172A",
    secondaryColor: "#F1F5F9",
    accentColor: "#475569",
    backgroundColor: "#F8FAFC",
    textColor: "#0F172A",
    fontFamily: "Playfair Display",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "none"
  },
  {
    id: "elegan-2",
    name: "Midnight Minimalist",
    category: "Elegan",
    primaryColor: "#94A3B8",
    secondaryColor: "#0F172A",
    accentColor: "#CBD5E1",
    backgroundColor: "linear-gradient(135deg, #090d16 0%, #0f172a 100%)",
    textColor: "#F8FAFC",
    fontFamily: "Montserrat",
    frameStyle: "modern",
    borderStyle: "double",
    particleType: "sparkle"
  },
  {
    id: "elegan-3",
    name: "Blush Champagne",
    category: "Elegan",
    primaryColor: "#C084FC",
    secondaryColor: "#FFF1F2",
    accentColor: "#E9D5FF",
    backgroundColor: "linear-gradient(135deg, #FAF5FF 0%, #FFF1F2 100%)",
    textColor: "#6B21A8",
    fontFamily: "Great Vibes",
    frameStyle: "floral",
    borderStyle: "classic",
    particleType: "flower"
  },
  {
    id: "elegan-4",
    name: "Gilded Marble",
    category: "Elegan",
    primaryColor: "#D1A153",
    secondaryColor: "#FAFAFA",
    accentColor: "#E8D5B5",
    backgroundColor: "#FFFFFF",
    textColor: "#2B2B2B",
    fontFamily: "Cinzel",
    frameStyle: "modern",
    borderStyle: "solid",
    particleType: "golden"
  },

  // 7. Korporat (4 templates)
  {
    id: "korporat-1",
    name: "Birokrat Biru Diraja",
    category: "Korporat",
    primaryColor: "#1E3A8A",
    secondaryColor: "#F8FAFC",
    accentColor: "#3B82F6",
    backgroundColor: "#FFFFFF",
    textColor: "#1E3A8A",
    fontFamily: "Montserrat",
    frameStyle: "modern",
    borderStyle: "solid",
    particleType: "none"
  },
  {
    id: "korporat-2",
    name: "Steel Professional",
    category: "Korporat",
    primaryColor: "#334155",
    secondaryColor: "#F1F5F9",
    accentColor: "#64748B",
    backgroundColor: "linear-gradient(135deg, #F8FAFC 0%, #E2E8F0 100%)",
    textColor: "#0F172A",
    fontFamily: "Montserrat",
    frameStyle: "modern",
    borderStyle: "double",
    particleType: "none"
  },
  {
    id: "korporat-3",
    name: "Platinum Executive",
    category: "Korporat",
    primaryColor: "#0F172A",
    secondaryColor: "#FFFFFF",
    accentColor: "#D1D5DB",
    backgroundColor: "#F3F4F6",
    textColor: "#111827",
    fontFamily: "Cinzel",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "none"
  },
  {
    id: "korporat-4",
    name: "Gold Prestige Corporate",
    category: "Korporat",
    primaryColor: "#D97706",
    secondaryColor: "#111827",
    accentColor: "#FBBF24",
    backgroundColor: "linear-gradient(135deg, #111827 0%, #1f2937 100%)",
    textColor: "#F9FAFB",
    fontFamily: "Montserrat",
    frameStyle: "modern",
    borderStyle: "double",
    particleType: "sparkle"
  },

  // 8. Minimalis (4 templates)
  {
    id: "minimalis-1",
    name: "Sederhana Bersih",
    category: "Minimalis",
    primaryColor: "#111111",
    secondaryColor: "#FFFFFF",
    accentColor: "#666666",
    backgroundColor: "#FFFFFF",
    textColor: "#111111",
    fontFamily: "Montserrat",
    frameStyle: "none",
    borderStyle: "none",
    particleType: "none"
  },
  {
    id: "minimalis-2",
    name: "Oatmeal Warm",
    category: "Minimalis",
    primaryColor: "#4B453D",
    secondaryColor: "#F5EFE6",
    accentColor: "#D8C4B6",
    backgroundColor: "#F5EFE6",
    textColor: "#4B453D",
    fontFamily: "Playfair Display",
    frameStyle: "none",
    borderStyle: "solid",
    particleType: "none"
  },
  {
    id: "minimalis-3",
    name: "Ash Grey Minimal",
    category: "Minimalis",
    primaryColor: "#2D3748",
    secondaryColor: "#EDF2F7",
    accentColor: "#A0AEC0",
    backgroundColor: "#F7FAFC",
    textColor: "#2D3748",
    fontFamily: "Montserrat",
    frameStyle: "none",
    borderStyle: "none",
    particleType: "none"
  },
  {
    id: "minimalis-4",
    name: "Sage Simple",
    category: "Minimalis",
    primaryColor: "#2F4F4F",
    secondaryColor: "#F4F7F4",
    accentColor: "#8FBC8F",
    backgroundColor: "#F4F7F4",
    textColor: "#2F4F4F",
    fontFamily: "Montserrat",
    frameStyle: "none",
    borderStyle: "none",
    particleType: "none"
  },

  // 9. Modern Glass (4 templates)
  {
    id: "modern-glass-1",
    name: "Frosted Cyan",
    category: "Modern Glass",
    primaryColor: "#06B6D4",
    secondaryColor: "#E0F7FA",
    accentColor: "#22D3EE",
    backgroundColor: "linear-gradient(135deg, #0e1e24 0%, #032b35 100%)",
    textColor: "#E0F7FA",
    fontFamily: "Montserrat",
    frameStyle: "glass",
    borderStyle: "solid",
    particleType: "firefly"
  },
  {
    id: "modern-glass-2",
    name: "Glassmorphism Rose",
    category: "Modern Glass",
    primaryColor: "#EC4899",
    secondaryColor: "#FFF0F3",
    accentColor: "#F472B6",
    backgroundColor: "linear-gradient(135deg, #240e15 0%, #3d051a 100%)",
    textColor: "#FFE4E6",
    fontFamily: "Great Vibes",
    frameStyle: "glass",
    borderStyle: "solid",
    particleType: "flower"
  },
  {
    id: "modern-glass-3",
    name: "Aurora Borealis",
    category: "Modern Glass",
    primaryColor: "#10B981",
    secondaryColor: "#EEFBF7",
    accentColor: "#6EE7B7",
    backgroundColor: "linear-gradient(135deg, #061f18 0%, #064e3b 100%)",
    textColor: "#E6F4EA",
    fontFamily: "Montserrat",
    frameStyle: "glass",
    borderStyle: "none",
    particleType: "sparkle"
  },
  {
    id: "modern-glass-4",
    name: "Sunset Gradient",
    category: "Modern Glass",
    primaryColor: "#F97316",
    secondaryColor: "#FFF7ED",
    accentColor: "#FDBA74",
    backgroundColor: "linear-gradient(135deg, #2d1502 0%, #542207 100%)",
    textColor: "#FFEDD5",
    fontFamily: "Montserrat",
    frameStyle: "glass",
    borderStyle: "double",
    particleType: "sparkle"
  },

  // 10. Premium Dark (4 templates)
  {
    id: "premium-dark-1",
    name: "Obsidian Silver",
    category: "Premium Dark",
    primaryColor: "#94A3B8",
    secondaryColor: "#030712",
    accentColor: "#F1F5F9",
    backgroundColor: "linear-gradient(135deg, #030712 0%, #111827 100%)",
    textColor: "#F1F5F9",
    fontFamily: "Cinzel",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "sparkle"
  },
  {
    id: "premium-dark-2",
    name: "Charcoal Minimal",
    category: "Premium Dark",
    primaryColor: "#F3F4F6",
    secondaryColor: "#111827",
    accentColor: "#9CA3AF",
    backgroundColor: "#1F2937",
    textColor: "#F9FAFB",
    fontFamily: "Montserrat",
    frameStyle: "none",
    borderStyle: "double",
    particleType: "none"
  },
  {
    id: "premium-dark-3",
    name: "Carbon & Gold",
    category: "Premium Dark",
    primaryColor: "#DFBA54",
    secondaryColor: "#1C1C1C",
    accentColor: "#FFD700",
    backgroundColor: "linear-gradient(135deg, #121212 0%, #1c1c1c 100%)",
    textColor: "#F5D77F",
    fontFamily: "Playfair Display",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "premium-dark-4",
    name: "Deep Space Neon",
    category: "Premium Dark",
    primaryColor: "#D946EF",
    secondaryColor: "#0F051D",
    accentColor: "#A21CAF",
    backgroundColor: "linear-gradient(135deg, #07020d 0%, #17072a 100%)",
    textColor: "#FAE8FF",
    fontFamily: "Montserrat",
    frameStyle: "modern",
    borderStyle: "solid",
    particleType: "firefly"
  },

  // 11. Royal (4 templates)
  {
    id: "royal-1",
    name: "Diraja Putrajaya",
    category: "Royal",
    primaryColor: "#DFBA54",
    secondaryColor: "#1E3A8A",
    accentColor: "#93C5FD",
    backgroundColor: "linear-gradient(135deg, #0f1c3f 0%, #1e3a8a 100%)",
    textColor: "#FCE7A2",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "golden"
  },
  {
    id: "royal-2",
    name: "Istana Baldu Kuning",
    category: "Royal",
    primaryColor: "#F59E0B",
    secondaryColor: "#451A03",
    accentColor: "#FDE047",
    backgroundColor: "linear-gradient(135deg, #2e1001 0%, #451a03 100%)",
    textColor: "#FCD34D",
    fontFamily: "Great Vibes",
    frameStyle: "royal",
    borderStyle: "double",
    particleType: "golden"
  },
  {
    id: "royal-3",
    name: "Sutera Ungu Diraja",
    category: "Royal",
    primaryColor: "#D946EF",
    secondaryColor: "#2E0854",
    accentColor: "#F472B6",
    backgroundColor: "linear-gradient(135deg, #1b0235 0%, #3a0e67 100%)",
    textColor: "#FCD34D",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "ornate",
    particleType: "sparkle"
  },
  {
    id: "royal-4",
    name: "Mahkota Perak",
    category: "Royal",
    primaryColor: "#E2E8F0",
    secondaryColor: "#0F172A",
    accentColor: "#94A3B8",
    backgroundColor: "linear-gradient(135deg, #020617 0%, #0f172a 100%)",
    textColor: "#F8FAFC",
    fontFamily: "Cinzel",
    frameStyle: "royal",
    borderStyle: "double",
    particleType: "sparkle"
  },

  // 12. Soft Pastel (6 templates)
  {
    id: "soft-pastel-1",
    name: "Mint Whispers",
    category: "Soft Pastel",
    primaryColor: "#10B981",
    secondaryColor: "#F0FDF4",
    accentColor: "#A7F3D0",
    backgroundColor: "#F0FDF4",
    textColor: "#065F46",
    fontFamily: "Montserrat",
    frameStyle: "classic",
    borderStyle: "dashed",
    particleType: "flower"
  },
  {
    id: "soft-pastel-2",
    name: "Blush Pink Sky",
    category: "Soft Pastel",
    primaryColor: "#EC4899",
    secondaryColor: "#FDF2F8",
    accentColor: "#FBCFE8",
    backgroundColor: "#FDF2F8",
    textColor: "#9D174D",
    fontFamily: "Alex Brush",
    frameStyle: "floral",
    borderStyle: "solid",
    particleType: "flower"
  },
  {
    id: "soft-pastel-3",
    name: "Lavender Breeze",
    category: "Soft Pastel",
    primaryColor: "#8B5CF6",
    secondaryColor: "#F5F3FF",
    accentColor: "#DDD6FE",
    backgroundColor: "#F5F3FF",
    textColor: "#5B21B6",
    fontFamily: "Playfair Display",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "sparkle"
  },
  {
    id: "soft-pastel-4",
    name: "Peach Chiffon",
    category: "Soft Pastel",
    primaryColor: "#F97316",
    secondaryColor: "#FFF7ED",
    accentColor: "#FFEDD5",
    backgroundColor: "#FFF7ED",
    textColor: "#9A3412",
    fontFamily: "Montserrat",
    frameStyle: "none",
    borderStyle: "solid",
    particleType: "flower"
  },
  {
    id: "soft-pastel-5",
    name: "Sky Cotton Candy",
    category: "Soft Pastel",
    primaryColor: "#06B6D4",
    secondaryColor: "#ECFEFF",
    accentColor: "#CFFAFE",
    backgroundColor: "#ECFEFF",
    textColor: "#155E75",
    fontFamily: "Montserrat",
    frameStyle: "classic",
    borderStyle: "solid",
    particleType: "snow"
  },
  {
    id: "soft-pastel-6",
    name: "Daisy Meadows",
    category: "Soft Pastel",
    primaryColor: "#EAB308",
    secondaryColor: "#FEFCE8",
    accentColor: "#FEF08A",
    backgroundColor: "#FEFCE8",
    textColor: "#854D0E",
    fontFamily: "Alex Brush",
    frameStyle: "floral",
    borderStyle: "dashed",
    particleType: "flower"
  }
];

// Helper to get default text style
export function createDefaultTextStyle(overrides: Partial<import("./types").TextStyle> = {}): import("./types").TextStyle {
  return {
    fontFamily: "Playfair Display",
    fontSize: 16,
    color: "#333333",
    isBold: false,
    isItalic: false,
    isUnderline: false,
    shadow: false,
    outline: false,
    glow: false,
    gradient: false,
    text3d: false,
    curve: false,
    opacity: 1,
    letterSpacing: 0,
    lineHeight: 1.5,
    rotate: 0,
    scale: 1,
    mirror: false,
    ...overrides
  };
}

// Pre-loaded initial retirement card content
export const DEFAULT_CARD_CONTENT: import("./types").CardContent = {
  id: "retirement-default",
  title: "MAJLIS PERSARAAN DAN KESYUKURAN",
  inviteeName: "Nik Norizan binti Nik Osman",
  designation: "Guru Kanan Sains & Matematik",
  agency: "SMK Hutan Pasir, Ketereh",
  dateStr: "27 Ogos 2026",
  dayStr: "Khamis",
  timeStr: "2.00 Petang",
  venue: "PT 1452, Kg Hutan Pasir, 16450 Ketereh, Kelantan",
  dressCode: "Baju Melayu / Kebaya Tradisional (Tema Pastel)",
  qrType: "maps",
  qrValue: "https://maps.app.goo.gl/v1xqFSMBaEVD5r4AA7g_st=ac",
  message: "Dengan penuh kesyukuran dan takzim, kami sekeluarga dengan segala hormatnya menjemput Dato'/Datin/Tuan/Puan/Encik/Cik ke Majlis Persaraan dan Kesyukuran sempena persaraan guru kesayangan kami.",
  prayer: "Ya Allah, berkatilah persaraan beliau, kurniakanlah kesihatan yang berpanjangan, kebahagiaan yang hakiki, dan lindungilah beliau dalam setiap langkahnya di fasa kehidupan yang baharu. Amin.",
  logoUrl: "", // Optional upload
  imageUrl: "/src/assets/images/main.jpg", // Preloaded main card image
  signatureUrl: "", // Optional digital signature
  bgMusicUrl: "https://youtu.be/FL02h4nRfvw?si=BA1TjxRrYBySJxQc", // YouTube background instrumental song requested
  bgMusicName: "Gamelan Warisan Melayu (Lagu Tema Utama)",
  gpsCoordinates: "5.9554, 102.2482",
  mapAddress: "PT 1452, Kg Hutan Pasir, 16450 Ketereh, Kelantan",
  activePage: "front",
  
  // Custom design overwrites (starts with Gold Luxury theme)
  primaryColor: "#DFBA54",
  secondaryColor: "#111111",
  backgroundColor: "linear-gradient(135deg, #111111 0%, #2a220f 100%)",
  textColor: "#FCE7A2",
  fontFamily: "Playfair Display",
  frameStyle: "royal",
  borderStyle: "double",
  particleType: "golden",
  
  positions: {
    title: { x: 50, y: 15 },
    inviteeName: { x: 50, y: 32 },
    designation: { x: 50, y: 44 },
    agency: { x: 50, y: 49 },
    dateTime: { x: 50, y: 62 },
    venue: { x: 50, y: 74 },
    dressCode: { x: 50, y: 84 },
    prayer: { x: 50, y: 92 }
  },
  
  textStyles: {
    title: createDefaultTextStyle({ fontSize: 28, isBold: true, color: "#DFBA54", fontFamily: "Playfair Display", letterSpacing: 2 }),
    inviteeName: createDefaultTextStyle({ fontSize: 34, isBold: true, color: "#FFFFFF", fontFamily: "Great Vibes", letterSpacing: 1 }),
    designation: createDefaultTextStyle({ fontSize: 16, color: "#E2E8F0", fontFamily: "Montserrat" }),
    agency: createDefaultTextStyle({ fontSize: 14, color: "#94A3B8", fontFamily: "Montserrat" }),
    dateTime: createDefaultTextStyle({ fontSize: 16, isBold: true, color: "#DFBA54", fontFamily: "Montserrat" }),
    venue: createDefaultTextStyle({ fontSize: 15, color: "#FFFFFF", fontFamily: "Montserrat" }),
    dressCode: createDefaultTextStyle({ fontSize: 13, isItalic: true, color: "#CBD5E1", fontFamily: "Montserrat" }),
    prayer: createDefaultTextStyle({ fontSize: 13, isItalic: true, color: "#94A3B8", fontFamily: "Amiri", lineHeight: 1.6 }),
    message: createDefaultTextStyle({ fontSize: 14, color: "#E2E8F0", fontFamily: "Montserrat", lineHeight: 1.5 })
  }
};
